### ISSUE TITLE
Store Entity data in a Database

### ISSUE THREAD

**Issue by MrVintage710** [two-shots-later/vitruvian-vtt#29]
# Proposed Feature
For persisting data, we need to agree and standardize a data format that can be stored locally. This data format must meet these design requirements:

- It must be as small as possible.
- Must be easy to write/read data, and must do it quickly
- Since Data for campaigns and rulebooks can add up, the data must be separated so that you don't need to load all of it into ram when operating with the data.
- must be supported for rust.

During the discovery process, there have been a couple options floating around:

- [rusqlite](https://github.com/rusqlite/rusqlite?tab=readme-ov-file)
- [candystore](https://github.com/sweet-security/candystore)
- [sled](https://github.com/spacejam/sled)

As part of this issue, all of these crates should be compared and tested to match the criteria.

# Acceptance Criteria
- [ ] Make sure all features are well documented with JSDoc. [Here is a guide for more info.](https://www.inkoop.io/blog/a-guide-to-js-docs-for-react-js/) 
- [ ] Compare and try all canidates, leaving a comment on issues that were run into and how well it mataches our requirements.
- [ ] After deciding the crate to use, write a easy and convenient system to save and load entities from disk.
- [ ] Create a mark down file that explains what is used to store data, and the format that the data is in. If there is a db schema, put that here.

**Comment by Gearhartlove** [comment]
I'm realizing that I don't have a clear vision of how to store our components efficiently and smartly. 

I'm reading up on this, one source I found builds their ecs from scratch: 
- part1: https://devlog.hexops.com/2022/lets-build-ecs-part-1/
- part2: https://devlog.hexops.com/2022/lets-build-ecs-part-2-databases/

**Comment by Gearhartlove** [comment]
We are switching gears to store data in sqlite, we will use stronger types vs generic entity component system.
