### ISSUE TITLE
Start to use 'cargo fmt' on each rust commit. 

### ISSUE THREAD

**Issue by Gearhartlove** [two-shots-later/vitruvian-vtt#39]
We need to go into src-types and src-tauri and ran 'cargo fmt' to start this flow. 

reasons for code formatting: 

Consistency: Code formatters ensure that code follows a consistent style throughout a project. This makes it easier for multiple developers to read and understand each other's code, as it adheres to the same conventions.

Readability: Well-formatted code is more readable. Proper indentation, spacing, and line breaks help in understanding the structure and flow of the code quickly.

Maintainability: Consistent formatting makes the code easier to maintain and modify. When code looks the same everywhere, it’s simpler to identify where changes need to be made and to understand the impact of those changes.

Collaboration: In team environments, code formatters reduce conflicts in version control systems by minimizing differences in formatting. This makes merging changes from different branches smoother and less error-prone.

Efficiency: Code formatters automate the process of styling code, saving developers time and mental effort. Developers can focus on writing the actual logic rather than worrying about formatting.

Professionalism: Clean, consistently formatted code reflects a level of professionalism and attention to detail, which can be important in a professional or open-source project.

Error Reduction: Properly formatted code can help in identifying syntax errors or logical mistakes. Misaligned code might hide bugs that are easier to spot when the code is neatly organized.

Adherence to Standards: Many code formatters follow industry or community standards, helping developers conform to best practices and widely accepted coding guidelines.

**Comment by MrVintage710** [comment]
I agree! This can only improve readability and streamline the project. I think that this should be something that is a apart of the repo. We should have a github action for running format. I will use this issue to start work on that.
