### ISSUE TITLE
Create a Button Component

### ISSUE THREAD

**Issue by MrVintage710** [two-shots-later/vitruvian-vtt#6]
![image](https://github.com/user-attachments/assets/014c68c8-6543-49fc-a1eb-1227c60d2f0a)

This issue is meant to create a component for buttons that can be used throughout the app.
This button should be able to change colors using a tailwind prop, and should have 

Figma Link: https://www.figma.com/design/pEKOr5N9RJqUNwGoFGXN1Q/Mockups?node-id=82-33&t=Lx76vdymKdNlyPqh-1

# Acceptance Criteria
- [ ] The component should be located at `src/components/Button.tsx`
- [ ] Make sure the component is well documented with JSDoc. [Here is a guide for more info.](https://www.inkoop.io/blog/a-guide-to-js-docs-for-react-js/)
- [ ] The component must have a story for the [storybook](https://storybook.js.org/docs). (Located at `src/stories`)
- [ ] A `color` prop that takes a tailwind color and applies that color to the button. The button fades from light to dark in a radial gradient. The middle color should be `color-400`, and the outer should be `color-600`.  Default for this value should be taken from the `useContext` hook for current color.
- [ ] A `size` prop that determines the button size should accept `default` and `small`. The `default` size should have a height of 3.0rems, and the the `small` size should have an overall height of 2.0rems.
- [ ] The button's Props type should extend `React.ButtonHTMLAttributes<HTMLButtonElement>` so the component can be used where ever a native button can be used.

example for buttons's type : 
```typescript
export type ButtonType = React.ButtonHTMLAttributes<HTMLButtonElement> & {
    // props go here
}
```

**Comment by AhmedBoumekla** [comment]
Hello, 
I'd like to work on the issue but the figma link doesn't work for me

**Comment by MrVintage710** [comment]
Also I just updated the issue for you. Welcome to the Team!

**Comment by Avinashshiyani** [comment]
I can help you with that and I can also provide more dynamicness

**Comment by MrVintage710** [comment]
Go right ahead @Avinashshiyani! Sorry I did not reply to this earlier, I am currently on vacation! If you need anything, let mw know! If you are actively working on this issue, go ahead and assign yourself to it. That way we can know who is working on any given issue so that we are not duplicating work. Let me know if you need any help with the code! I will check occasionally while I travel.

**Comment by Avinashshiyani** [comment]
> Go right ahead @Avinashshiyani! Sorry I did not reply to this earlier, I am currently on vacation! If you need anything, let mw know! If you are actively working on this issue, go ahead and assign yourself to it. That way we can know who is working on any given issue so that we are not duplicating work. Let me know if you need any help with the code! I will check occasionally while I travel.

sorry to say sir/mam but  i only know react not typescript and rust i am facing many difficulties in tauri and tsx if it was just react with vite it will be a toffee for me

**Comment by Avinashshiyani** [comment]
> No problem! For this issue you would not need any tauri knowledge! However, having that knowledge may not hurt while working on this project. Admittedly it is pretty early days for the project and there could be more support to help newcomers make commits. Keep checking in on the project, and soon it should be in a place that you could help!

Yes i will track the project and thanks for understanding me
